# Generated by Django 3.0.2 on 2020-01-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('profile_text', models.TextField(null=True)),
                ('trashtalk', models.CharField(choices=[('NO', 'Nybegynner')], default='NO', max_length=5)),
            ],
        ),
    ]
